language: nix
nix: 2.3.7
sudo: false

env:
  global:
  - CACHIX_CACHE=jefdaj

install:
- echo "trusted-users = $USER" | sudo tee -a /etc/nix/nix.conf
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo launchctl kickstart -k system/org.nixos.nix-daemon && sleep 5 || true; else sudo systemctl restart nix-daemon; fi
- nix-env -iA nixpkgs.cachix
- cachix use $CACHIX_CACHE

matrix:
  fast_finish: true
  include:
  - os: linux
    dist: xenial
    env: NIX_PATH=nixpkgs=channel:nixos-21.05
  - os: osx
    osx_image: xcode10.1
    env: NIX_PATH=nixpkgs=channel:nixpkgs-21.05-darwin

git:
  # quiet: true
  depth: 5

script:
  - nix-build release.nix
  - ./result/bin/raxmlHPC-MPI -h

notifications:
  email:
  on_success: false
  on_failure: false
